In [285]:
import dare
import numpy as np
import pandas as pd
import random
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [286]:
data = pd.read_csv("cleaned_loan.csv")
data

,Pekerjaan,Jenis Pinjaman,Plafon (Rp.),Kondisi Joint Income,Kondisi Pisah Harta,Usia,Hasil IDEB SLIK OJK,Tujuan Pemilikan Properti,Lama bekerja,Penghasilan,...,Down Payment,Asset lainnya yang dimiliki,Bidang Usaha,Ukuran Perusahaan,Kondisi Sertifikat Agunan Utama,Jenis Bangunan Utama,Kondisi Properti Utama,Keputusan,Kelayakan Dokumen Pendukung,Keputusan Akhir
0,KARYAWAN,"PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL","Plafon (< 514,750,000)",TIDAK JOINT INCOME,TIDAK PISAH HARTA,21 - 35,Data Tidak Tersedia,Rumah Tinggal (Rumah ke 1),"≥ 2, < 5",SINGLE : ≥RP 10 JUTA,...,>= 15%,DEPOSITO/INVES/EMAS ≥ LIMIT KREDIT,"Keuangan, asuransi, perbankan",Cakupan area : nasional,"SHM, SERTIPIKAT PECAH",Rumah Tinggal,READY STOK,GREEN,LAYAK,Diterima
1,PENGUSAHA,"PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL","Plafon (> 1,340,960,436)",TIDAK JOINT INCOME,PISAH HARTA,36 - 45,"Kol 1, Tidak pernah menunggak",Rumah Tinggal (Rumah ke 1),≥ 5,MENIKAH : ≥RP 20 JUTA,...,>= 15%,DEPOSITO/INVES/EMAS ≥ LIMIT KREDIT,Lainnya,Cakupan area : nasional,"SHM, SERTIPIKAT PECAH",Rumah Tinggal,READY STOK,GREEN,LAYAK,Diterima
2,KARYAWAN,"TAKE OVER + TOP UP KPR, RUMAH TINGGAL","Plafon (> 1,340,960,436)",JOINT INCOME,TIDAK PISAH HARTA,46 - 55,"Kol 1, Tidak pernah menunggak",Rumah Tinggal (Rumah ke 1),≥ 5,MENIKAH : ≥RP 20 JUTA,...,>= 15%,PROPERTI/KENDARAAN ≥ LIMIT KREDIT,KLINIK AKUPUNTIR,CAKUPAN AREA : LOKAL,"SHM, SERTIPIKAT PECAH",Rumah Tinggal,SEDANG DIHUNI,GREEN,LAYAK,Diterima
3,PENGUSAHA,"PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL","Plafon (894,632,536 - 1,340,960,436)",JOINT INCOME,TIDAK PISAH HARTA,36 - 45,"Kol 1, Tidak pernah menunggak",RUMAH TINGGAL (RUMAH KE 2/3),≥ 5,MENIKAH : ≥RP 20 JUTA,...,>= 15%,PROPERTI/KENDARAAN < 100% LIMIT KREDIT,PERDAGANGAN,CAKUPAN AREA : LOKAL,"SHM, SERTIPIKAT PECAH",RUKO/RUKAN,READY STOK,GREEN,LAYAK,Diterima
4,KARYAWAN,"PEMBELIAN BEKAS / SECONDARY, RUMAH TINGGAL","Plafon (< 514,750,000)",JOINT INCOME,TIDAK PISAH HARTA,21 - 35,Data Tidak Tersedia,Rumah Tinggal (Rumah ke 1),"≥ 2, < 5","SINGLE : ≥RP 6 JUTA, < RP. 10 JUTA",...,>= 15%,KAS DAN NON KAS ≥ LIMIT KREDIT,COLOUR SALON,CAKUPAN AREA : LOKAL,"SHGB, SERTIPIKAT PECAH",Rumah Tinggal,SEDANG DIHUNI,YELLOW,LAYAK,Diterima
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,KARYAWAN,"Pembelian Baru / Primary, Rumah Tinggal > Tipe 70","Plafon (> 1,340,960,436)",TIDAK JOINT INCOME,TIDAK PISAH HARTA,21 - 35,"Kol 1, Tidak pernah menunggak",Rumah Tinggal (Rumah ke 1),"≥ 2, < 5",SINGLE : ≥RP 20 JUTA,...,>= 15%,Properti/kendaraan < 50% plafon,"INFORMASI, TELEKOMUNIKASI DAN KOMPUTER",Public listed,MOU - Sertipikat Induk,Rumah Tinggal,Indent,YELLOW,TIDAK,Ditolak
196,KARYAWAN,"Pembelian Baru / Primary, Rumah Tinggal Tipe 2...","Plafon (< 514,750,000)",JOINT INCOME,TIDAK PISAH HARTA,21 - 35,Data Tidak Tersedia,Rumah Tinggal (Rumah ke 1),≥ 5,"MENIKAH : ≥RP 10 JUTA, <RP 20 JUTA",...,>= 15%,DEPOSITO/INVES/EMAS < 50% plafon,Lainnya,Multinasional,"SHGB, SERTIPIKAT PECAH",Rumah Tinggal,Indent,GREEN,TIDAK,Ditolak
197,KARYAWAN,"Pembelian Baru / Primary, Rumah Tinggal Tipe 2...","Plafon (< 514,750,000)",TIDAK JOINT INCOME,TIDAK PISAH HARTA,21 - 35,"Kol 1, Tidak pernah menunggak",Rumah Tinggal (Rumah ke 1),"≥ 2, < 5","SINGLE : ≥RP 6 JUTA, < RP. 10 JUTA",...,>= 15%,DEPOSITO/INVES/EMAS < 50% plafon,Lainnya,CAKUPAN AREA : LOKAL,MOU - Sertipikat Induk,Rumah Tinggal,Indent,YELLOW,TIDAK,Ditolak
198,PENGUSAHA,"Pembelian Baru / Primary, Ruko / Rukan","Plafon (> 1,340,960,436)",TIDAK JOINT INCOME,PISAH HARTA,56 - 65,"Kol 1, Tidak pernah menunggak",Rumah Tinggal (Rumah ke 1),≥ 5,MENIKAH : ≥RP 20 JUTA,...,>= 15%,null < 50% plafon,Lainnya,Multinasional,MOU - Sertipikat Induk,RUKO/RUKAN,Indent,GREEN,TIDAK,Ditolak
199,KARYAWAN,"Pembelian Baru / Primary, Apartemen Tipe 22 - 70","Plafon (514,750,000 - 894,632,536)",TIDAK JOINT INCOME,TIDAK PISAH HARTA,46 - 55,"Kol 1, Tidak pernah menunggak",Rumah Tinggal (Rumah ke 1),≥ 5,SINGLE : ≥RP 20 JUTA,...,>= 15%,Properti/kendaraan < 50% plafon,"Keuangan, asuransi, perbankan",Cakupan area : nasional,MOU - Sertipikat Induk,Apartemen,Indent,GREEN,TIDAK,Ditolak

In [287]:
labelEncoder = {}
for col in data.columns:
    le = LabelEncoder()
    data[col] = le.fit_transform(data[col])
    labelEncoder[col] = le
data

,Pekerjaan,Jenis Pinjaman,Plafon (Rp.),Kondisi Joint Income,Kondisi Pisah Harta,Usia,Hasil IDEB SLIK OJK,Tujuan Pemilikan Properti,Lama bekerja,Penghasilan,...,Down Payment,Asset lainnya yang dimiliki,Bidang Usaha,Ukuran Perusahaan,Kondisi Sertifikat Agunan Utama,Jenis Bangunan Utama,Kondisi Properti Utama,Keputusan,Kelayakan Dokumen Pendukung,Keputusan Akhir
0,0,1,2,1,1,0,0,2,1,5,...,1,2,14,1,6,2,1,0,0,0
1,1,1,3,1,0,1,8,2,2,3,...,1,2,15,1,6,2,1,0,0,0
2,0,9,3,0,1,2,8,2,2,3,...,1,9,12,0,6,2,2,0,0,0
3,1,1,1,0,1,1,8,1,2,3,...,1,7,19,0,6,1,1,0,0,0
4,0,1,2,0,1,0,0,2,1,8,...,1,5,2,0,3,2,2,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0,6,3,1,1,0,8,2,1,7,...,1,10,6,4,0,2,0,2,1,1
196,0,7,2,0,1,0,0,2,2,2,...,1,1,15,3,3,2,0,0,1,1
197,0,7,2,1,1,0,8,2,1,8,...,1,1,15,0,0,2,0,2,1,1
198,1,5,3,1,0,3,8,2,2,3,...,1,12,15,3,0,1,0,0,1,1
199,0,4,0,1,1,2,8,2,2,7,...,1,10,14,1,0,0,0,0,1,1

In [288]:
X = data.drop(["Keputusan Akhir"], axis=1)
y = data["Keputusan Akhir"]

In [289]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [290]:
X_train

,Pekerjaan,Jenis Pinjaman,Plafon (Rp.),Kondisi Joint Income,Kondisi Pisah Harta,Usia,Hasil IDEB SLIK OJK,Tujuan Pemilikan Properti,Lama bekerja,Penghasilan,...,Jangka Waktu Kredit,Down Payment,Asset lainnya yang dimiliki,Bidang Usaha,Ukuran Perusahaan,Kondisi Sertifikat Agunan Utama,Jenis Bangunan Utama,Kondisi Properti Utama,Keputusan,Kelayakan Dokumen Pendukung
79,1,1,3,1,0,1,8,2,2,3,...,1,1,9,23,0,6,2,1,0,0
197,0,7,2,1,1,0,8,2,1,8,...,0,1,1,15,0,0,2,0,2,1
38,0,1,2,1,1,0,8,2,2,2,...,1,1,5,21,0,3,2,1,0,0
24,0,4,0,1,1,2,4,2,2,3,...,1,1,12,14,1,0,0,4,2,1
122,1,6,3,0,1,2,0,2,2,3,...,0,1,12,15,0,0,2,4,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0,4,2,1,1,1,8,2,2,3,...,1,1,12,27,1,0,0,4,0,0
14,0,4,0,1,1,0,8,2,1,5,...,0,0,10,15,0,0,0,4,2,0
92,0,6,1,1,0,2,0,2,0,2,...,0,1,10,23,1,0,2,0,2,0
179,0,7,0,1,1,0,8,1,2,6,...,0,0,12,5,3,0,2,0,1,1
102,1,7,3,1,1,0,6,2,1,3,...,0,1,12,23,0,0,2,0,0,0

In [291]:
y_train

79     0
197    1
38     0
24     1
122    0
      ..
106    0
14     1
92     1
179    1
102    0
Name: Keputusan Akhir, Length: 160, dtype: int32

In [292]:
X_train = np.array(X_train.values.tolist())

In [293]:
y_train = np.array(y_train.values.tolist())

In [294]:
X_test = np.array(X_test.values.tolist())

In [295]:
X_train

array([[1, 1, 3, ..., 1, 0, 0],
       [0, 7, 2, ..., 0, 2, 1],
       [0, 1, 2, ..., 1, 0, 0],
       ...,
       [0, 6, 1, ..., 0, 2, 0],
       [0, 7, 0, ..., 0, 1, 1],
       [1, 7, 3, ..., 0, 0, 0]])

In [296]:
y_train

array([0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0])

In [297]:
rf = dare.Forest(n_estimators=100, max_depth=5, k = 5, topd = 0, random_state=1)

In [298]:
rf.fit(X_train, y_train)

In [299]:
y_pred = rf.predict(X_test)

In [300]:
accuracy = accuracy_score(y_pred, y_test)
print(f"Akurasi Model DaRE Forest : {accuracy}")

Akurasi Model DaRE Forest : 0.95

In [301]:
exp_results = pd.DataFrame(columns=['Iteration', 'Accuracy'])
exp_results

Empty DataFrame
Columns: [Iteration, Accuracy]
Index: []

In [302]:
deleted_index = []

In [303]:
iterations = 1
deleted_index = []
max_random_number = 159

In [304]:
while accuracy > 0.7 and rf.manager_.n_samples > 0:
    new_index = False
    while new_index == False:
        index = random.randint(0, max_random_number)
        if index not in deleted_index:
            deleted_index.append(index)
            break
    print("index: ", index)
    print("n_sample:", rf.manager_.n_samples)
    rf.delete(index)
    y_pred = rf.predict(X_test)
    accuracy = accuracy_score(y_pred, y_test)
    exp_results = pd.concat([exp_results, pd.DataFrame([{'Iteration': iterations, 'Accuracy': accuracy}])], ignore_index=True)
    iterations += 1

index:  16
n_sample: 160
index:  129
n_sample: 159
index:  40
n_sample: 158
index:  97
n_sample: 157
index:  130
n_sample: 156
index:  47
n_sample: 155
index:  84
n_sample: 154
index:  10
n_sample: 153
index:  107
n_sample: 152
index:  103
n_sample: 151
index:  43
n_sample: 150
index:  98
n_sample: 149
index:  99
n_sample: 148
index:  150
n_sample: 147
index:  65
n_sample: 146
index:  29
n_sample: 145
index:  39
n_sample: 144
index:  42
n_sample: 143
index:  46
n_sample: 142
index:  123
n_sample: 141
index:  56
n_sample: 140
index:  120
n_sample: 139
index:  35
n_sample: 138
index:  30
n_sample: 137
index:  93
n_sample: 136
index:  82
n_sample: 135
index:  153
n_sample: 134
index:  102
n_sample: 133
index:  66
n_sample: 132
index:  55
n_sample: 131
index:  1
n_sample: 130
index:  58
n_sample: 129
index:  18
n_sample: 128
index:  75
n_sample: 127
index:  53
n_sample: 126
index:  11
n_sample: 125
index:  12
n_sample: 124
index:  138
n_sample: 123
index:  25
n_sample: 122
index:  96
n_sample: 121
index:  24
n_sample: 120
index:  28
n_sample: 119
index:  111
n_sample: 118
index:  147
n_sample: 117
index:  139
n_sample: 116
index:  4
n_sample: 115
index:  21
n_sample: 114
index:  32
n_sample: 113
index:  92
n_sample: 112
index:  124
n_sample: 111
index:  159
n_sample: 110
index:  31
n_sample: 109
index:  108
n_sample: 108
index:  13
n_sample: 107
index:  91
n_sample: 106
index:  106
n_sample: 105
index:  83
n_sample: 104
index:  50
n_sample: 103
index:  122
n_sample: 102
index:  34
n_sample: 101
index:  71
n_sample: 100
index:  44
n_sample: 99
index:  141
n_sample: 98
index:  14
n_sample: 97
index:  113
n_sample: 96
index:  136
n_sample: 95
index:  88
n_sample: 94
index:  148
n_sample: 93
index:  143
n_sample: 92
index:  64
n_sample: 91
index:  8
n_sample: 90
index:  78
n_sample: 89
index:  20
n_sample: 88
index:  127
n_sample: 87
index:  146
n_sample: 86
index:  68
n_sample: 85
index:  38
n_sample: 84
index:  132
n_sample: 83
index:  45
n_sample: 82
index:  115
n_sample: 81
index:  155
n_sample: 80
index:  3
n_sample: 79
index:  48
n_sample: 78
index:  128
n_sample: 77
index:  151
n_sample: 76
index:  137
n_sample: 75
index:  7
n_sample: 74
index:  37
n_sample: 73
index:  22
n_sample: 72
index:  89
n_sample: 71
index:  73
n_sample: 70
index:  15
n_sample: 69
index:  0
n_sample: 68
index:  69
n_sample: 67
index:  51
n_sample: 66
index:  142
n_sample: 65
index:  134
n_sample: 64
index:  26
n_sample: 63
index:  72
n_sample: 62
index:  144
n_sample: 61
index:  67
n_sample: 60
index:  105
n_sample: 59
index:  36
n_sample: 58
index:  121
n_sample: 57
index:  95
n_sample: 56
index:  27
n_sample: 55
index:  9
n_sample: 54
index:  158
n_sample: 53
index:  125
n_sample: 52
index:  90
n_sample: 51
index:  131
n_sample: 50
index:  54
n_sample: 49
index:  6
n_sample: 48
index:  33
n_sample: 47
index:  23
n_sample: 46
index:  81
n_sample: 45
index:  2
n_sample: 44
index:  112
n_sample: 43
index:  100
n_sample: 42
index:  152
n_sample: 41
index:  79
n_sample: 40
index:  62
n_sample: 39
index:  76
n_sample: 38
index:  109
n_sample: 37
index:  149
n_sample: 36
index:  57
n_sample: 35
index:  156
n_sample: 34
index:  133
n_sample: 33
index:  114
n_sample: 32
index:  70
n_sample: 31
index:  118
n_sample: 30

In [305]:
data_result = pd.DataFrame(exp_results)
data_result

    Iteration  Accuracy
0           1     0.950
1           2     0.950
2           3     0.950
3           4     0.950
4           5     0.950
..        ...       ...
126       127     0.775
127       128     0.750
128       129     0.775
129       130     0.800
130       131     0.700

[131 rows x 2 columns]

In [306]:
print(len(deleted_index))

131

In [307]:
remaining_index = []
for i in range(160):
    if i in deleted_index:
        continue
    else:
        remaining_index.append(i)

In [308]:
print(remaining_index)

[5, 17, 19, 41, 49, 52, 59, 60, 61, 63, 74, 77, 80, 85, 86, 87, 94, 101, 104, 110, 116, 117, 119, 126, 135, 140, 145, 154, 157]

In [310]:
X_train_new = []
y_train_new = []
for i in remaining_index:
    X_train_new.append(X_train[i])
    y_train_new.append(y_train[i])

In [311]:
import xgboost as xgb
xgb_model = xgb.XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')

In [312]:
xgb_model.fit(X_train_new, y_train_new)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, random_state=None, ...)

In [313]:
y_pred_xgb = xgb_model.predict(X_test)

In [314]:
accuracy = accuracy_score(y_pred_xgb, y_test)
print(f"Akurasi Model XGBOOST : {accuracy}")

Akurasi Model XGBOOST : 0.875